version: '3.8'

services:
  trading-dashboard:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    container_name: real-time-trading-dashboard
